from manual_test.manual_test_base import \
    ManualTestBase, \
    handle_command_line, \
    CLEAN_SERVER_RECORD_TYPE, \
    POPULATED_SERVER_RECORD_TYPE
from manual_test.utilities.workspace_utilities import WorkspaceUtilities
from typing import Any, Dict, List

SERVICE_NAME = 'Security'
DATABASE_NAME = 'auth'
TEST_NAME = 'SecurityMigrationTest'
ROUTE = '/niuser/v1'
USER_ROUTE = ROUTE + '/users'
QUERY_USER_ROUTE = USER_ROUTE + '/query'
AUTH_MAPPING_ROUTE = ROUTE + '/auth-mappings'
AUTH_POLICY_TEMPLATE_ROUTE = '/niauth/v1/policy-templates'
RECORDED_DATA_IDENTIFIER = 'security'


class TestSecurity(ManualTestBase):
    def populate_data(self) -> None:
        self.__populate_server_with_test_data()
        self.__record_populated_server_security_data()

    def record_initial_data(self) -> None:
        self.__record_clean_server_security_data()

    def validate_data(self) -> None:
        source_service_snapshot = self.__read_populated_server_security_data()
        target_service_snapshot = self.__read_clean_server_security_data()
        current_snapshot = self.__get_all_security_data()
        self.__validate_user_migration(current_snapshot, source_service_snapshot, target_service_snapshot)
        self.__validate_workspace_migration(current_snapshot, source_service_snapshot)
        self.__validate_auth_mapping_migration(current_snapshot, source_service_snapshot, target_service_snapshot)

    def __validate_user_migration(self, current_snapshot, source_service_snapshot, target_service_snapshot):
        users_source_service_snapshot = source_service_snapshot['users']
        users_target_service_snapshot = target_service_snapshot['users']
        users_current_snapshot = current_snapshot['users']
        for user in users_current_snapshot:
            expected_user = self.find_record_with_matching_id(user, users_source_service_snapshot)
            if expected_user is not None:
                self.__assert_users_equal(expected_user, user)
            else:
                # Verify items that are generated by the target version and not present in the source.
                expected_user = self.find_record_by_property_value(user, users_target_service_snapshot, 'login')
                assert expected_user is not None
                self.__assert_rules_equal(expected_user, user)

    def __validate_workspace_migration(self, current_snapshot, source_service_snapshot):
        workspaces_source_service_snapshot = source_service_snapshot['workspaces']
        workspaces_current_snapshot = current_snapshot['workspaces']
        for source_workspace in workspaces_source_service_snapshot:
            assert source_workspace in workspaces_current_snapshot

    def __validate_auth_mapping_migration(self, current_snapshot, source_service_snapshot, target_service_snapshot):
        mappings_source_snapshot = source_service_snapshot['auth_mappings']
        mappings_target_snapshot = target_service_snapshot['auth_mappings']
        mappings_current_snapshot = current_snapshot['auth_mappings']
        for mapping in mappings_current_snapshot:
            expected_mapping = self.find_record_with_matching_id(mapping, mappings_source_snapshot)
            if expected_mapping is not None:
                self.__assert_workspaces_equal(expected_mapping, mapping)
            else:
                # Verify items that are generated by the target version and not present in the source.
                expected_mapping = self.find_record_by_property_value(mapping, mappings_target_snapshot, 'name')
                assert expected_mapping is not None
                self.__assert_workspaces_equal(expected_mapping, mapping)

    def __populate_server_with_test_data(self):
        workspace_utilities = WorkspaceUtilities()
        workspace_utilities.create_workspace_for_test(self)
        built_in_policy_template = self.__get_built_in_policy_templates()[0]
        self.__create_test_user()
        for workspace in workspace_utilities.get_two_or_more_workspaces(self):
            self.__create_test_policy_template()
            self.__create_test_auth_mapping(workspace, built_in_policy_template['id'])

    @staticmethod
    def __assert_users_equal(expected_user, user):
        TestSecurity.__assert_dictionaries_equal(expected_user, user, ['updated'])

    @staticmethod
    def __assert_workspaces_equal(expected_workspace, workspace):
        assert expected_workspace == workspace

    def __create_test_auth_mapping(self, workspace_id: str, policy_template_id: str):
        auth_mapping = {
            'type': 'windows-user',
            'policyTemplateId': policy_template_id,
            'workspace': workspace_id,
            'selector': {
                'key': 'user',
                'value': 'test'
            }
        }
        response = self.post(AUTH_MAPPING_ROUTE, json=auth_mapping)
        response.raise_for_status()

    def __create_test_user(self):
        user = {
            'firstName': 'firstname',
            'lastName': 'lastname',
            'email': 'firstname@lastname.net',
            'niuaId': 'niuaId',
            'login': 'firstname',
            'acceptedToS': 'true',
            'policies': [],
            'keywords': [],
            'properties': {},
        }
        response = self.post(USER_ROUTE, json=user)
        response.raise_for_status()

    def __create_test_policy_template(self):
        policy_template = {
          'name': 'test-policy-template',
          'type': 'user',
          'statements': [
            {
              'actions': [
                'alarm:Read',
                'alarm:Transition',
                'alarm:AddNote'
              ],
              'resource': [
                '*'
              ],
              'description': 'testdescription'
            }
          ],
        }
        response = self.post(AUTH_POLICY_TEMPLATE_ROUTE, json=policy_template)
        response.raise_for_status()

    def __record_clean_server_security_data(self):
        self.record_json_data(
            SERVICE_NAME,
            RECORDED_DATA_IDENTIFIER,
            CLEAN_SERVER_RECORD_TYPE,
            self.__get_all_security_data())

    def __record_populated_server_security_data(self):
        self.record_json_data(
            SERVICE_NAME,
            RECORDED_DATA_IDENTIFIER,
            POPULATED_SERVER_RECORD_TYPE,
            self.__get_all_security_data())

    def __read_clean_server_security_data(self):
        return self.read_recorded_json_data(
            SERVICE_NAME,
            RECORDED_DATA_IDENTIFIER,
            CLEAN_SERVER_RECORD_TYPE,
            required=True)

    def __read_populated_server_security_data(self):
        return self.read_recorded_json_data(
            SERVICE_NAME,
            RECORDED_DATA_IDENTIFIER,
            POPULATED_SERVER_RECORD_TYPE,
            required=True)

    def __get_all_security_data(self) -> Dict[str, Any]:
        workspace_utilities = WorkspaceUtilities()
        workspaces = workspace_utilities.get_workspaces(self)
        users = self.__get_all_user_data()
        auth_mappings = self.__get_all_auth_mappings()
        return {
            'workspaces': workspaces,
            'users': users,
            'auth_mappings': auth_mappings,
        }

    def __get_all_user_data(self) -> List[Dict[str, Any]]:
        query: Dict[str, str] = {}
        response = self.post(QUERY_USER_ROUTE, json=query)
        response.raise_for_status()
        return response.json()['users']

    def __get_all_auth_mappings(self):
        query: Dict[str, str] = {}
        response = self.get(AUTH_MAPPING_ROUTE, json=query)
        response.raise_for_status()
        return response.json()['authMappings']

    def __get_all_policy_templates(self):
        response = self.get(AUTH_POLICY_TEMPLATE_ROUTE)
        response.raise_for_status()
        return response.json()['policyTemplates']

    def __get_built_in_policy_templates(self):
        return [policy for policy in self.__get_all_policy_templates() if policy['builtIn']]

    @staticmethod
    def __assert_dictionaries_equal(expected, actual, keys_to_not_compare):
        expected_excluding_ignored = set(expected).difference(keys_to_not_compare)
        actual_excluding_ignored = set(actual).difference(keys_to_not_compare)
        assert all(expected[key] == actual[key] for key in expected_excluding_ignored)
        assert expected_excluding_ignored == actual_excluding_ignored


if __name__ == '__main__':
    handle_command_line(TestSecurity)
